# Copyright 2025 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Autogenerated by pycargoebuild 0.15.0

EAPI=8

inherit cargo

DESCRIPTION="Podlet generates Podman Quadlet files from a Podman command, compose file, or existing object."
HOMEPAGE="https://github.com/containers/podlet"
SRC_URI="
	https://github.com/containers/podlet/releases/download/v${PV}/source.tar.gz
	https://github.com/nuclear06/gentoo-deps/releases/download/${P}/${P}-crates.tar.xz
"
DEPEND="
"
RDEPEND="${DEPEND}"

LICENSE="MPL-2.0"
SLOT="0"
KEYWORDS="~amd64"
RUST_MIN_VERSION="1.85.0"
