# Copyright 2025 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Autogenerated by pycargoebuild 0.15.0

EAPI=8

inherit cargo git-r3

DESCRIPTION="CLI Tool for codeberg similar to gh and glab"
HOMEPAGE="https://codeberg.org/Aviac/codeberg-cli"
EGIT_REPO_URI="https://codeberg.org/Aviac/codeberg-cli.git"
SRC_URI=""

LICENSE="AGPL-3+"
# Dependent crate licenses
LICENSE+=" Apache-2.0 BSD ISC MIT MPL-2.0 Unicode-3.0"
SLOT="0"
KEYWORDS=""

DEPEND="
	dev-libs/openssl:=
"
RDEPEND="${DEPEND}"

src_unpack() {
	git-r3_src_unpack
	cargo_live_src_unpack
}